import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { test, expect, provider, upload, showChat, originalVisible } from './helpers.mjs'

test.beforeEach(async ({ request }) => provider(request))

test('Stream Markdown, citations, reload, real container restart and new chat', async ({ page, request }) => {
  test.setTimeout(240_000)
  const doc = await upload(page, 'sample.docx')
  await showChat(page)
  await provider(request, { hold_stream: true })
  await page.getByLabel('Сообщение для чата', { exact: true }).fill('Кратко перескажи документ')
  await page.getByRole('button', { name: 'Отправить вопрос', exact: true }).click()
  await expect(page.locator('.assistant-message strong')).toHaveText('Синтетический ответ')
  await expect(page.getByRole('button', { name: 'Отправить вопрос', exact: true })).toBeDisabled()
  await provider(request)
  await expect(page.locator('.assistant-message li')).toHaveCount(2)
  await expect(page.locator('.assistant-message h2')).toHaveText('Итог')
  await expect(page.locator('.assistant-message table')).toContainText('Готово')
  await expect(page.locator('.assistant-message blockquote')).toContainText('Тестовая цитата')
  await expect(page.locator('.assistant-message pre code')).toContainText("print('synthetic')")
  expect(await page.evaluate(() => window.__unsafeChatExecuted)).toBeUndefined()
  await expect(page.getByLabel('Сообщение для чата', { exact: true })).toBeEnabled()
  await expect(page.locator('.assistant-message .inline-citation').first()).toBeVisible()
  const chats = await (await request.get('/api/v1/chats')).json()
  const chat = chats.find(item => item.document_id === doc.id)
  expect(chat).toBeTruthy()
  await expect.poll(async () => (await (await request.get(`/api/v1/chats/${chat.id}/messages`)).json()).length).toBe(2)
  const saved = await (await request.get(`/api/v1/chats/${chat.id}/messages`)).json()
  expect(saved[1].citations.length).toBeGreaterThan(0)
  await page.reload()
  await showChat(page)
  await expect(page.locator('.assistant-message li')).toHaveCount(2)
  const compose = ['compose', '-p', 'document-checker-e2e', '-f', 'compose.e2e.yml']
  for (const service of ['db', 'api', 'worker', 'web']) {
    execFileSync('docker', [...compose, 'restart', service], { cwd: path.resolve('..'), timeout: 90_000 })
    execFileSync('docker', [...compose, 'up', '-d', '--wait', '--wait-timeout', '120', service], { cwd: path.resolve('..'), timeout: 150_000 })
  }
  await expect.poll(async () => {
    try { return (await request.get('/api/v1/documents')).status() } catch { return 0 }
  }, { timeout: 90_000 }).toBe(200)
  await page.reload()
  await expect(page.locator('.insight-card')).toHaveCount(7)
  await showChat(page)
  await expect(page.locator('.assistant-message li')).toHaveCount(2)
  const restored = await (await request.get(`/api/v1/chats/${chat.id}/messages`)).json()
  expect(restored).toEqual(saved)
  await originalVisible(page, 'docx')
  await page.getByRole('button', { name: 'Новый чат', exact: true }).click()
  await expect(page.getByRole('heading', { name: /Загрузите документ/ })).toBeVisible()
  await expect(page.getByLabel('Вопрос по документу', { exact: true })).toBeDisabled()
  await expect(page.locator('.assistant-message')).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: /Загрузите документ/ })).toBeVisible()
  await page.locator('.document-select').filter({ hasText: 'Кратко перескажи' }).first().click()
  await expect(page.locator('.assistant-message li')).toHaveCount(2)
})

test('No evidence and provider stream error are explicit and recoverable', async ({ page, request }) => {
  await upload(page, 'sample.txt')
  await showChat(page)
  await page.getByLabel('Сообщение для чата', { exact: true }).fill('нет доказательств')
  await page.getByRole('button', { name: 'Отправить вопрос', exact: true }).click()
  await expect(page.locator('.assistant-message').last()).toContainText('не найдено достаточно подтверждений')
  await provider(request, { mode: 'stream_error' })
  await page.getByLabel('Сообщение для чата', { exact: true }).fill('Проверить ошибку')
  await page.getByRole('button', { name: 'Отправить вопрос', exact: true }).click()
  await expect(page.locator('.toast-message')).toContainText('Не удалось получить ответ от Codex')
  await provider(request)
  await expect(page.getByLabel('Сообщение для чата', { exact: true })).toBeEnabled()
  await originalVisible(page, 'text')
})

for (const [width, height] of [[1440,900], [1280,720], [1024,768], [768,1024], [430,932], [390,844]]) {
  test(`Panels, fit-to-width, keyboard preferences: ${width}×${height}`, async ({ page }) => {
    await page.setViewportSize({ width, height })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await upload(page, 'sample.docx')
    if (width < 600) await page.getByRole('button', { name: 'Открыть документы', exact: true }).click()
    await page.getByRole('button', { name: 'Свернуть библиотеку', exact: true }).click()
    await expect.poll(() => page.locator('#chat-library').evaluate(element => Math.round(element.getBoundingClientRect().width))).toBe(72)
    await page.reload()
    if (width < 600) await page.getByRole('button', { name: 'Открыть документы', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Развернуть библиотеку', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Развернуть библиотеку', exact: true }).click()
    await expect.poll(() => page.locator('#chat-library').evaluate(element => Math.round(element.getBoundingClientRect().width))).toBe(width < 600 ? 300 : 240)
    if (width < 600) await page.getByRole('button', { name: 'Закрыть открытые панели', exact: true }).click({ position: { x: width - 5, y: 150 } })
    await originalVisible(page, 'docx')
    await expect.poll(() => page.locator('.docx-render-host').evaluate(host => {
      const sheet = host.querySelector('section.docx-preview').getBoundingClientRect()
      return sheet.width <= host.clientWidth + 2
    }), { message: 'DOCX page fits the viewer after its responsive scale is applied' }).toBeTruthy()
    const toggle = page.locator('.chat-visibility-toggle')
    await toggle.click()
    await expect(toggle).toBeVisible()
    await toggle.click()
    await expect(toggle).toBeVisible()
    // Close mobile overlay before accessing the top bar settings.
    if (width < 600 && await toggle.getAttribute('aria-expanded') === 'true') await toggle.click()
    await page.locator('.connection-button').click()
    await page.getByRole('button', { name: /^Модель:/ }).click()
    await expect(page.getByRole('option')).toHaveCount(2)
    await page.getByRole('option', { name: /GPT-6.1 Sol/ }).click()
    await expect(page.getByRole('button', { name: 'Модель: GPT-6.1 Sol' })).toBeVisible()
    await page.getByRole('button', { name: /^Уровень анализа:/ }).click()
    await page.getByRole('option', { name: /^High/ }).click()
    await expect(page.getByRole('button', { name: 'Уровень анализа: High', exact: true })).toBeVisible()
    await page.getByRole('button', { name: /^Модель:/ }).click()
    await page.keyboard.press('End')
    await page.keyboard.press('Escape')
    await expect(page.getByRole('button', { name: /^Модель:/ })).toBeFocused()
    await page.getByRole('dialog').getByRole('button', { name: 'Закрыть', exact: true }).click()
    await page.reload()
    await expect(page.locator('.connection-button')).toHaveAttribute('aria-label', /GPT-6.1 Sol, High/)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
    await page.screenshot({ path: `test-results/viewport-${width}x${height}.png`, fullPage: true })
  })
}

test('Delete confirmation cancels safely, then removes only the selected synthetic chat', async ({ page, request }) => {
  const doc = await upload(page, 'sample.txt')
  const chats = await (await request.get('/api/v1/chats')).json()
  const count = chats.length
  // The library is sorted by recency; this test's newly uploaded chat is first.
  const row = page.locator('.library .row-actions-trigger').first()
  await row.click()
  await page.getByRole('menuitem', { name: 'Удалить документ и чат', exact: true }).click()
  await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  expect((await request.get(`/api/v1/documents/${doc.id}`)).status()).toBe(200)
  await row.click()
  await page.getByRole('menuitem', { name: 'Удалить документ и чат', exact: true }).click()
  await page.getByRole('button', { name: 'Удалить документ', exact: true }).click()
  await expect.poll(async () => (await request.get(`/api/v1/documents/${doc.id}`)).status()).toBe(404)
  expect((await (await request.get('/api/v1/chats')).json()).length).toBe(count - 1)
  await page.reload()
  await expect(page.locator('.assistant-message')).toHaveCount(0)
})
